#!/bin/bash

# Test OpenRouter Fallback for CV Builder
# This script simulates rate limit scenarios

echo "========================================="
echo "OpenRouter Fallback Test"
echo "========================================="
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Check environment
echo "Checking configuration..."
cd /home/desire/My_Project/TalentSphere/backend

if grep -q "OPENROUTER_API_KEY=" .env 2>/dev/null; then
    echo -e "${GREEN}✓${NC} OPENROUTER_API_KEY found in .env"
else
    echo -e "${RED}✗${NC} OPENROUTER_API_KEY not found in .env"
    echo -e "${YELLOW}⚠${NC}  Fallback will not work without OpenRouter API key"
    echo ""
    echo "To enable fallback, add to .env:"
    echo "OPENROUTER_API_KEY=your_key_here"
fi

if grep -q "GEMINI_API_KEY=" .env 2>/dev/null; then
    echo -e "${GREEN}✓${NC} GEMINI_API_KEY found in .env"
else
    echo -e "${RED}✗${NC} GEMINI_API_KEY not found in .env"
fi

echo ""
echo "========================================="
echo "Improved Rate Limit Handling Features"
echo "========================================="
echo ""
echo "1. ✅ Automatic OpenRouter Fallback"
echo "   - Detects Gemini rate limit errors"
echo "   - Automatically switches to OpenRouter"
echo "   - No user intervention needed"
echo ""
echo "2. ✅ Smart API Selection"
echo "   - Remembers when Gemini quota exhausted"
echo "   - Uses OpenRouter directly for next requests"
echo "   - Reduces unnecessary retry attempts"
echo ""
echo "3. ✅ Enhanced Error Detection"
echo "   - Detects multiple rate limit patterns:"
echo "     • 429 status codes"
echo "     • RESOURCE_EXHAUSTED errors"
echo "     • 'quota' and 'rate limit' messages"
echo "     • 'requests per minute/day' patterns"
echo ""
echo "4. ✅ Better User Messages"
echo "   - Clear indication when fallback activates"
echo "   - Shows which API is being used"
echo "   - Suggests configuring OpenRouter key if missing"
echo ""
echo "5. ✅ Exponential Backoff"
echo "   - Waits 2s, 4s, 8s between retries"
echo "   - Respects API suggested retry delays"
echo "   - Prevents hammering the API"
echo ""
echo "========================================="
echo "How It Works"
echo "========================================="
echo ""
echo "When Gemini Rate Limit is Hit:"
echo ""
echo "1️⃣  First Request:"
echo "   ├─ Try Gemini API"
echo "   ├─ Rate limit hit → Wait 2s"
echo "   ├─ Retry → Still rate limited → Wait 4s"
echo "   ├─ Retry → Still rate limited → Wait 8s"
echo "   └─ After 3 retries: Switch to OpenRouter ✅"
echo ""
echo "2️⃣  Subsequent Requests:"
echo "   ├─ Detect Gemini quota exhausted"
echo "   └─ Use OpenRouter directly ✅ (skip Gemini retries)"
echo ""
echo "3️⃣  If OpenRouter Also Fails:"
echo "   └─ Report both errors to user"
echo ""
echo "========================================="
echo "Configuration Tips"
echo "========================================="
echo ""
echo "Get OpenRouter API Key (Free Tier):"
echo "1. Visit: https://openrouter.ai/"
echo "2. Sign up for free account"
echo "3. Get API key from dashboard"
echo "4. Add to backend/.env:"
echo "   OPENROUTER_API_KEY=sk-or-v1-xxxxx"
echo ""
echo "Free Tier Limits:"
echo "• OpenRouter: Generous free credits"
echo "• Gemini: 15 req/min, 1500 req/day"
echo ""
echo "========================================="
echo "Testing Recommendations"
echo "========================================="
echo ""
echo "To test the fallback:"
echo "1. Generate multiple CVs quickly to hit Gemini limit"
echo "2. Watch console logs for fallback activation"
echo "3. Verify OpenRouter API is used automatically"
echo ""
echo "Expected Console Output on Fallback:"
echo "  [CV Builder] ⚠️ Gemini rate limit exhausted after 3 retries"
echo "  [CV Builder] 🔄 Automatically switching to OpenRouter API..."
echo "  [CV Builder] ✅ OpenRouter API succeeded"
echo ""
echo "========================================="
echo "Test Complete"
echo "========================================="
